#############################################################################
# Makefile for building: TaskSpider.app/Contents/MacOS/TaskSpider
# Generated by qmake (3.1) (Qt 6.6.0)
# Project:  TaskSpider.pro
# Template: app
# Command: /Users/Mura/Qt/6.6.0/macos/bin/qmake -o Makefile TaskSpider.pro -spec macx-clang CONFIG+=debug CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = /Library/Developer/CommandLineTools/usr/bin/clang
CXX           = /Library/Developer/CommandLineTools/usr/bin/clang++
DEFINES       = -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=11.0 -Wall -Wextra $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -g -std=gnu++1z $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=11.0 -Wall -Wextra $(DEFINES)
INCPATH       = -I. -I../Qt/6.6.0/macos/lib/QtWidgets.framework/Headers -I../Qt/6.6.0/macos/lib/QtGui.framework/Headers -I../Qt/6.6.0/macos/lib/QtCore.framework/Headers -I. -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/AGL.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/AGL.framework/Headers -I../Qt/6.6.0/macos/mkspecs/macx-clang -F/Users/Mura/Qt/6.6.0/macos/lib
QMAKE         = /Users/Mura/Qt/6.6.0/macos/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /Users/Mura/Qt/6.6.0/macos/bin/qmake -install qinstall
QINSTALL_PROGRAM = /Users/Mura/Qt/6.6.0/macos/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = TaskSpider1.0.0
DISTDIR = /Users/Mura/Task2_Spider/.tmp/TaskSpider1.0.0
LINK          = /Library/Developer/CommandLineTools/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=11.0 -Wl,-rpath,@executable_path/../Frameworks -Wl,-rpath,/Users/Mura/Qt/6.6.0/macos/lib
LIBS          = $(SUBLIBS) -F/Users/Mura/Qt/6.6.0/macos/lib -framework QtWidgets -framework QtGui -framework AppKit -framework ImageIO -framework Metal -framework QtCore -framework IOKit -framework DiskArbitration -framework AGL -framework OpenGL   
AR            = /Library/Developer/CommandLineTools/usr/bin/ar cq
RANLIB        = /Library/Developer/CommandLineTools/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		spider.cpp \
		widget.cpp moc_spider.cpp \
		moc_widget.cpp
OBJECTS       = main.o \
		spider.o \
		widget.o \
		moc_spider.o \
		moc_widget.o
DIST          = README.md \
		img/pauk.png \
		pauk.png \
		../Qt/6.6.0/macos/mkspecs/features/spec_pre.prf \
		../Qt/6.6.0/macos/mkspecs/features/device_config.prf \
		../Qt/6.6.0/macos/mkspecs/common/unix.conf \
		../Qt/6.6.0/macos/mkspecs/common/mac.conf \
		../Qt/6.6.0/macos/mkspecs/common/macx.conf \
		../Qt/6.6.0/macos/mkspecs/common/sanitize.conf \
		../Qt/6.6.0/macos/mkspecs/common/gcc-base.conf \
		../Qt/6.6.0/macos/mkspecs/common/gcc-base-mac.conf \
		../Qt/6.6.0/macos/mkspecs/common/clang.conf \
		../Qt/6.6.0/macos/mkspecs/common/clang-mac.conf \
		../Qt/6.6.0/macos/mkspecs/qconfig.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_ext_freetype.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_ext_libjpeg.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_ext_libpng.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_concurrent.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_concurrent_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_core.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_core_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_dbus.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_dbus_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_designer.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_designer_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_example_icons_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_fb_support_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_freetype_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_gui.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_gui_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_harfbuzz_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_help.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_help_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_jpeg_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_labsanimation.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_labsanimation_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_labssettings.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_labssettings_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_labssharedimage.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_linguist.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_linguist_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_network.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_network_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_opengl.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_opengl_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_openglwidgets.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_png_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_printsupport.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_printsupport_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qdoccatch_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qdoccatchconversionsprivate.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qdoccatchconversionsprivate_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qdoccatchgeneratorsprivate.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qdoccatchgeneratorsprivate_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qml.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qml_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmlcompiler.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmlcore.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmlcore_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmldom_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmlintegration.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmlintegration_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmlls_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmlmodels.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmltest.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmltest_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmltoolingsettings_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quick.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quick_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quickdialogs2.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quickeffects_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quicklayouts.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quickwidgets.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_sql.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_sql_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_svg.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_svg_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_svgwidgets.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_testlib.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_testlib_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_tools_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_uiplugin.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_uitools.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_uitools_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_widgets.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_widgets_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_xml.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_xml_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_plugin_qdarwinbluetoothpermission.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_plugin_qdarwincalendarpermission.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_plugin_qdarwincamerapermission.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_plugin_qdarwincontactspermission.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_plugin_qdarwinlocationpermission.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_plugin_qdarwinmicrophonepermission.pri \
		../Qt/6.6.0/macos/mkspecs/features/qt_functions.prf \
		../Qt/6.6.0/macos/mkspecs/features/qt_config.prf \
		../Qt/6.6.0/macos/mkspecs/macx-clang/qmake.conf \
		../Qt/6.6.0/macos/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../Qt/6.6.0/macos/mkspecs/features/exclusive_builds.prf \
		../Qt/6.6.0/macos/mkspecs/features/mac/sdk.prf \
		../Qt/6.6.0/macos/mkspecs/features/toolchain.prf \
		../Qt/6.6.0/macos/mkspecs/features/mac/toolchain.prf \
		../Qt/6.6.0/macos/mkspecs/features/default_pre.prf \
		../Qt/6.6.0/macos/mkspecs/features/mac/default_pre.prf \
		../Qt/6.6.0/macos/mkspecs/features/resolve_config.prf \
		../Qt/6.6.0/macos/mkspecs/features/default_post.prf \
		../Qt/6.6.0/macos/mkspecs/features/mac/default_post.prf \
		../Qt/6.6.0/macos/mkspecs/features/mac/objective_c.prf \
		../Qt/6.6.0/macos/mkspecs/features/qml_debug.prf \
		../Qt/6.6.0/macos/mkspecs/features/mac/mac.prf \
		../Qt/6.6.0/macos/mkspecs/features/warn_on.prf \
		../Qt/6.6.0/macos/mkspecs/features/permissions.prf \
		../Qt/6.6.0/macos/mkspecs/features/qt.prf \
		../Qt/6.6.0/macos/mkspecs/features/resources_functions.prf \
		../Qt/6.6.0/macos/mkspecs/features/resources.prf \
		../Qt/6.6.0/macos/mkspecs/features/moc.prf \
		../Qt/6.6.0/macos/mkspecs/features/unix/opengl.prf \
		../Qt/6.6.0/macos/mkspecs/features/uic.prf \
		../Qt/6.6.0/macos/mkspecs/features/unix/thread.prf \
		../Qt/6.6.0/macos/mkspecs/features/qmake_use.prf \
		../Qt/6.6.0/macos/mkspecs/features/file_copies.prf \
		../Qt/6.6.0/macos/mkspecs/features/mac/rez.prf \
		../Qt/6.6.0/macos/mkspecs/features/mac/asset_catalogs.prf \
		../Qt/6.6.0/macos/mkspecs/features/testcase_targets.prf \
		../Qt/6.6.0/macos/mkspecs/features/exceptions.prf \
		../Qt/6.6.0/macos/mkspecs/features/yacc.prf \
		../Qt/6.6.0/macos/mkspecs/features/lex.prf \
		TaskSpider.pro spider.h \
		widget.h main.cpp \
		spider.cpp \
		widget.cpp
QMAKE_TARGET  = TaskSpider
DESTDIR       = 
TARGET        = TaskSpider.app/Contents/MacOS/TaskSpider

####### Custom Variables
EXPORT_QMAKE_MAC_SDK = macosx
EXPORT_QMAKE_MAC_SDK_VERSION = 14.0
EXPORT_QMAKE_XCODE_DEVELOPER_PATH = /Library/Developer/CommandLineTools
EXPORT__QMAKE_STASH_ = /Users/Mura/Task2_Spider/.qmake.stash
EXPORT_VALID_ARCHS = x86_64 arm64
EXPORT_DEFAULT_ARCHS = x86_64
EXPORT_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(if $(ARCHS), $(ARCHS), $(if $(EXPORT_DEFAULT_ARCHS), $(EXPORT_DEFAULT_ARCHS), $(EXPORT_VALID_ARCHS))))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ARCHS), $(EXPORT_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))
EXPORT__PRO_FILE_ = /Users/Mura/Task2_Spider/TaskSpider.pro


include /Users/Mura/Qt/6.6.0/macos/mkspecs/features/mac/sdk.mk
first: all
####### Build rules

TaskSpider.app/Contents/MacOS/TaskSpider:  $(OBJECTS)  
	@test -d TaskSpider.app/Contents/MacOS/ || mkdir -p TaskSpider.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET)  $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: TaskSpider.pro ../Qt/6.6.0/macos/mkspecs/macx-clang/qmake.conf ../Qt/6.6.0/macos/mkspecs/features/spec_pre.prf \
		../Qt/6.6.0/macos/mkspecs/features/device_config.prf \
		../Qt/6.6.0/macos/mkspecs/common/unix.conf \
		../Qt/6.6.0/macos/mkspecs/common/mac.conf \
		../Qt/6.6.0/macos/mkspecs/common/macx.conf \
		../Qt/6.6.0/macos/mkspecs/common/sanitize.conf \
		../Qt/6.6.0/macos/mkspecs/common/gcc-base.conf \
		../Qt/6.6.0/macos/mkspecs/common/gcc-base-mac.conf \
		../Qt/6.6.0/macos/mkspecs/common/clang.conf \
		../Qt/6.6.0/macos/mkspecs/common/clang-mac.conf \
		../Qt/6.6.0/macos/mkspecs/qconfig.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_ext_freetype.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_ext_libjpeg.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_ext_libpng.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_concurrent.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_concurrent_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_core.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_core_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_dbus.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_dbus_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_designer.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_designer_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_example_icons_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_fb_support_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_freetype_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_gui.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_gui_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_harfbuzz_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_help.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_help_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_jpeg_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_labsanimation.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_labsanimation_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_labssettings.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_labssettings_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_labssharedimage.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_linguist.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_linguist_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_network.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_network_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_opengl.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_opengl_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_openglwidgets.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_png_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_printsupport.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_printsupport_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qdoccatch_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qdoccatchconversionsprivate.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qdoccatchconversionsprivate_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qdoccatchgeneratorsprivate.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qdoccatchgeneratorsprivate_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qml.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qml_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmlcompiler.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmlcore.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmlcore_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmldom_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmlintegration.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmlintegration_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmlls_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmlmodels.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmltest.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmltest_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmltoolingsettings_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quick.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quick_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quickdialogs2.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quickeffects_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quicklayouts.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quickwidgets.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_sql.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_sql_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_svg.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_svg_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_svgwidgets.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_testlib.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_testlib_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_tools_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_uiplugin.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_uitools.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_uitools_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_widgets.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_widgets_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_xml.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_lib_xml_private.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_plugin_qdarwinbluetoothpermission.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_plugin_qdarwincalendarpermission.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_plugin_qdarwincamerapermission.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_plugin_qdarwincontactspermission.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_plugin_qdarwinlocationpermission.pri \
		../Qt/6.6.0/macos/mkspecs/modules/qt_plugin_qdarwinmicrophonepermission.pri \
		../Qt/6.6.0/macos/mkspecs/features/qt_functions.prf \
		../Qt/6.6.0/macos/mkspecs/features/qt_config.prf \
		../Qt/6.6.0/macos/mkspecs/macx-clang/qmake.conf \
		../Qt/6.6.0/macos/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../Qt/6.6.0/macos/mkspecs/features/exclusive_builds.prf \
		../Qt/6.6.0/macos/mkspecs/features/mac/sdk.prf \
		../Qt/6.6.0/macos/mkspecs/features/toolchain.prf \
		../Qt/6.6.0/macos/mkspecs/features/mac/toolchain.prf \
		../Qt/6.6.0/macos/mkspecs/features/default_pre.prf \
		../Qt/6.6.0/macos/mkspecs/features/mac/default_pre.prf \
		../Qt/6.6.0/macos/mkspecs/features/resolve_config.prf \
		../Qt/6.6.0/macos/mkspecs/features/default_post.prf \
		../Qt/6.6.0/macos/mkspecs/features/mac/default_post.prf \
		../Qt/6.6.0/macos/mkspecs/features/mac/objective_c.prf \
		../Qt/6.6.0/macos/mkspecs/features/qml_debug.prf \
		../Qt/6.6.0/macos/mkspecs/features/mac/mac.prf \
		../Qt/6.6.0/macos/mkspecs/features/warn_on.prf \
		../Qt/6.6.0/macos/mkspecs/features/permissions.prf \
		../Qt/6.6.0/macos/mkspecs/features/qt.prf \
		../Qt/6.6.0/macos/mkspecs/features/resources_functions.prf \
		../Qt/6.6.0/macos/mkspecs/features/resources.prf \
		../Qt/6.6.0/macos/mkspecs/features/moc.prf \
		../Qt/6.6.0/macos/mkspecs/features/unix/opengl.prf \
		../Qt/6.6.0/macos/mkspecs/features/uic.prf \
		../Qt/6.6.0/macos/mkspecs/features/unix/thread.prf \
		../Qt/6.6.0/macos/mkspecs/features/qmake_use.prf \
		../Qt/6.6.0/macos/mkspecs/features/file_copies.prf \
		../Qt/6.6.0/macos/mkspecs/features/mac/rez.prf \
		../Qt/6.6.0/macos/mkspecs/features/mac/asset_catalogs.prf \
		../Qt/6.6.0/macos/mkspecs/features/testcase_targets.prf \
		../Qt/6.6.0/macos/mkspecs/features/exceptions.prf \
		../Qt/6.6.0/macos/mkspecs/features/yacc.prf \
		../Qt/6.6.0/macos/mkspecs/features/lex.prf \
		TaskSpider.pro \
		../Qt/6.6.0/macos/lib/QtWidgets.framework/Resources/QtWidgets.prl \
		../Qt/6.6.0/macos/lib/QtGui.framework/Resources/QtGui.prl \
		../Qt/6.6.0/macos/lib/QtCore.framework/Resources/QtCore.prl
	$(QMAKE) -o Makefile TaskSpider.pro -spec macx-clang CONFIG+=debug CONFIG+=qml_debug
../Qt/6.6.0/macos/mkspecs/features/spec_pre.prf:
../Qt/6.6.0/macos/mkspecs/features/device_config.prf:
../Qt/6.6.0/macos/mkspecs/common/unix.conf:
../Qt/6.6.0/macos/mkspecs/common/mac.conf:
../Qt/6.6.0/macos/mkspecs/common/macx.conf:
../Qt/6.6.0/macos/mkspecs/common/sanitize.conf:
../Qt/6.6.0/macos/mkspecs/common/gcc-base.conf:
../Qt/6.6.0/macos/mkspecs/common/gcc-base-mac.conf:
../Qt/6.6.0/macos/mkspecs/common/clang.conf:
../Qt/6.6.0/macos/mkspecs/common/clang-mac.conf:
../Qt/6.6.0/macos/mkspecs/qconfig.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_ext_freetype.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_ext_libjpeg.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_ext_libpng.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_lib_concurrent.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_lib_concurrent_private.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_lib_core.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_lib_core_private.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_lib_dbus.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_lib_dbus_private.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_lib_designer.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_lib_designer_private.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_lib_designercomponents_private.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_lib_example_icons_private.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_lib_fb_support_private.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_lib_freetype_private.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_lib_gui.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_lib_gui_private.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_lib_harfbuzz_private.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_lib_help.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_lib_help_private.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_lib_jpeg_private.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_lib_labsanimation.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_lib_labsanimation_private.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_lib_labsfolderlistmodel.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_lib_labsqmlmodels.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_lib_labsqmlmodels_private.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_lib_labssettings.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_lib_labssettings_private.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_lib_labssharedimage.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_lib_labssharedimage_private.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_lib_labswavefrontmesh.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_lib_linguist.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_lib_linguist_private.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_lib_network.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_lib_network_private.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_lib_opengl.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_lib_opengl_private.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_lib_openglwidgets.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_lib_openglwidgets_private.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_lib_png_private.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_lib_printsupport.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_lib_printsupport_private.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qdoccatch_private.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qdoccatchconversionsprivate.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qdoccatchconversionsprivate_private.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qdoccatchgeneratorsprivate.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qdoccatchgeneratorsprivate_private.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qml.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qml_private.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmlcompiler.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmlcompiler_private.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmlcore.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmlcore_private.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmldebug_private.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmldom_private.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmlintegration.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmlintegration_private.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmllocalstorage.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmllocalstorage_private.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmlls_private.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmlmodels.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmlmodels_private.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmltest.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmltest_private.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmltoolingsettings_private.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmlworkerscript.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmlxmllistmodel.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quick.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quick_private.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quickcontrols2.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quickcontrols2impl.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quickdialogs2.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quickdialogs2_private.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quickdialogs2utils.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quickeffects_private.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quicklayouts.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quicklayouts_private.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quickparticles_private.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quickshapes_private.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quicktemplates2.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quickwidgets.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_lib_sql.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_lib_sql_private.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_lib_svg.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_lib_svg_private.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_lib_svgwidgets.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_lib_svgwidgets_private.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_lib_testlib.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_lib_testlib_private.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_lib_tools_private.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_lib_uiplugin.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_lib_uitools.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_lib_uitools_private.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_lib_widgets.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_lib_widgets_private.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_lib_xml.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_lib_xml_private.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_plugin_qdarwinbluetoothpermission.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_plugin_qdarwincalendarpermission.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_plugin_qdarwincamerapermission.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_plugin_qdarwincontactspermission.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_plugin_qdarwinlocationpermission.pri:
../Qt/6.6.0/macos/mkspecs/modules/qt_plugin_qdarwinmicrophonepermission.pri:
../Qt/6.6.0/macos/mkspecs/features/qt_functions.prf:
../Qt/6.6.0/macos/mkspecs/features/qt_config.prf:
../Qt/6.6.0/macos/mkspecs/macx-clang/qmake.conf:
../Qt/6.6.0/macos/mkspecs/features/spec_post.prf:
.qmake.stash:
../Qt/6.6.0/macos/mkspecs/features/exclusive_builds.prf:
../Qt/6.6.0/macos/mkspecs/features/mac/sdk.prf:
../Qt/6.6.0/macos/mkspecs/features/toolchain.prf:
../Qt/6.6.0/macos/mkspecs/features/mac/toolchain.prf:
../Qt/6.6.0/macos/mkspecs/features/default_pre.prf:
../Qt/6.6.0/macos/mkspecs/features/mac/default_pre.prf:
../Qt/6.6.0/macos/mkspecs/features/resolve_config.prf:
../Qt/6.6.0/macos/mkspecs/features/default_post.prf:
../Qt/6.6.0/macos/mkspecs/features/mac/default_post.prf:
../Qt/6.6.0/macos/mkspecs/features/mac/objective_c.prf:
../Qt/6.6.0/macos/mkspecs/features/qml_debug.prf:
../Qt/6.6.0/macos/mkspecs/features/mac/mac.prf:
../Qt/6.6.0/macos/mkspecs/features/warn_on.prf:
../Qt/6.6.0/macos/mkspecs/features/permissions.prf:
../Qt/6.6.0/macos/mkspecs/features/qt.prf:
../Qt/6.6.0/macos/mkspecs/features/resources_functions.prf:
../Qt/6.6.0/macos/mkspecs/features/resources.prf:
../Qt/6.6.0/macos/mkspecs/features/moc.prf:
../Qt/6.6.0/macos/mkspecs/features/unix/opengl.prf:
../Qt/6.6.0/macos/mkspecs/features/uic.prf:
../Qt/6.6.0/macos/mkspecs/features/unix/thread.prf:
../Qt/6.6.0/macos/mkspecs/features/qmake_use.prf:
../Qt/6.6.0/macos/mkspecs/features/file_copies.prf:
../Qt/6.6.0/macos/mkspecs/features/mac/rez.prf:
../Qt/6.6.0/macos/mkspecs/features/mac/asset_catalogs.prf:
../Qt/6.6.0/macos/mkspecs/features/testcase_targets.prf:
../Qt/6.6.0/macos/mkspecs/features/exceptions.prf:
../Qt/6.6.0/macos/mkspecs/features/yacc.prf:
../Qt/6.6.0/macos/mkspecs/features/lex.prf:
TaskSpider.pro:
../Qt/6.6.0/macos/lib/QtWidgets.framework/Resources/QtWidgets.prl:
../Qt/6.6.0/macos/lib/QtGui.framework/Resources/QtGui.prl:
../Qt/6.6.0/macos/lib/QtCore.framework/Resources/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile TaskSpider.pro -spec macx-clang CONFIG+=debug CONFIG+=qml_debug

qmake_all: FORCE

TaskSpider.app/Contents/PkgInfo: 
	@test -d TaskSpider.app/Contents || mkdir -p TaskSpider.app/Contents
	@$(DEL_FILE) TaskSpider.app/Contents/PkgInfo
	@echo "APPL????" > TaskSpider.app/Contents/PkgInfo
TaskSpider.app/Contents/Info.plist: 
	@test -d TaskSpider.app/Contents || mkdir -p TaskSpider.app/Contents
	@$(DEL_FILE) TaskSpider.app/Contents/Info.plist
	@plutil -convert xml1 -o - ../Qt/6.6.0/macos/mkspecs/macx-clang/Info.plist.app | sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,\$${QMAKE_SHORT_VERSION},1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,\$${QMAKE_FULL_VERSION},1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" -e "s,@BUNDLEIDENTIFIER@,com.yourcompany.TaskSpider,g" -e "s,\$${PRODUCT_BUNDLE_IDENTIFIER},com.yourcompany.TaskSpider,g" -e "s,\$${MACOSX_DEPLOYMENT_TARGET},11.0,g" -e "s,\$${IPHONEOS_DEPLOYMENT_TARGET},,g" -e "s,\$${TVOS_DEPLOYMENT_TARGET},,g" -e "s,\$${WATCHOS_DEPLOYMENT_TARGET},,g" -e "s,\$${IOS_LAUNCH_SCREEN},LaunchScreen,g" -e "s,@ICON@,,g" -e "s,\$${ASSETCATALOG_COMPILER_APPICON_NAME},,g" -e "s,@EXECUTABLE@,TaskSpider,g" -e "s,@LIBRARY@,TaskSpider,g" -e "s,\$${EXECUTABLE_NAME},TaskSpider,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" >TaskSpider.app/Contents/Info.plist

all: Makefile \
		TaskSpider.app/Contents/PkgInfo \
		TaskSpider.app/Contents/Info.plist TaskSpider.app/Contents/MacOS/TaskSpider

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents spider.h widget.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp spider.cpp widget.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r TaskSpider.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

xcodeproj:
	@$(QMAKE) -spec macx-xcode "$(EXPORT__PRO_FILE_)" -spec macx-clang CONFIG+=debug CONFIG+=qml_debug

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_spider.cpp moc_widget.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_spider.cpp moc_widget.cpp
moc_spider.cpp: spider.h \
		../Qt/6.6.0/macos/lib/QtCore.framework/Headers/QObject \
		../Qt/6.6.0/macos/lib/QtCore.framework/Headers/qobject.h \
		../Qt/6.6.0/macos/lib/QtCore.framework/Headers/QPoint \
		../Qt/6.6.0/macos/lib/QtCore.framework/Headers/qpoint.h \
		../Qt/6.6.0/macos/lib/QtCore.framework/Headers/QLine \
		../Qt/6.6.0/macos/lib/QtCore.framework/Headers/qline.h \
		../Qt/6.6.0/macos/lib/QtCore.framework/Headers/QRect \
		../Qt/6.6.0/macos/lib/QtCore.framework/Headers/qrect.h \
		../Qt/6.6.0/macos/libexec/moc
	/Users/Mura/Qt/6.6.0/macos/libexec/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -D__cplusplus=199711L -D__APPLE_CC__=6000 -D__clang__ -D__clang_major__=15 -D__clang_minor__=0 -D__clang_patchlevel__=0 -D__GNUC__=4 -D__GNUC_MINOR__=2 -D__GNUC_PATCHLEVEL__=1 -I/Users/Mura/Qt/6.6.0/macos/mkspecs/macx-clang -I/Users/Mura/Task2_Spider -I/Users/Mura/Qt/6.6.0/macos/lib/QtWidgets.framework/Headers -I/Users/Mura/Qt/6.6.0/macos/lib/QtGui.framework/Headers -I/Users/Mura/Qt/6.6.0/macos/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/15.0.0/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/usr/include -F/Users/Mura/Qt/6.6.0/macos/lib spider.h -o moc_spider.cpp

moc_widget.cpp: widget.h \
		../Qt/6.6.0/macos/lib/QtWidgets.framework/Headers/QWidget \
		../Qt/6.6.0/macos/lib/QtWidgets.framework/Headers/qwidget.h \
		../Qt/6.6.0/macos/lib/QtCore.framework/Headers/QTimer \
		../Qt/6.6.0/macos/lib/QtCore.framework/Headers/qtimer.h \
		../Qt/6.6.0/macos/libexec/moc
	/Users/Mura/Qt/6.6.0/macos/libexec/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -D__cplusplus=199711L -D__APPLE_CC__=6000 -D__clang__ -D__clang_major__=15 -D__clang_minor__=0 -D__clang_patchlevel__=0 -D__GNUC__=4 -D__GNUC_MINOR__=2 -D__GNUC_PATCHLEVEL__=1 -I/Users/Mura/Qt/6.6.0/macos/mkspecs/macx-clang -I/Users/Mura/Task2_Spider -I/Users/Mura/Qt/6.6.0/macos/lib/QtWidgets.framework/Headers -I/Users/Mura/Qt/6.6.0/macos/lib/QtGui.framework/Headers -I/Users/Mura/Qt/6.6.0/macos/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/15.0.0/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/usr/include -F/Users/Mura/Qt/6.6.0/macos/lib widget.h -o moc_widget.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

main.o: main.cpp ../Qt/6.6.0/macos/lib/QtWidgets.framework/Headers/QApplication \
		../Qt/6.6.0/macos/lib/QtWidgets.framework/Headers/qapplication.h \
		widget.h \
		../Qt/6.6.0/macos/lib/QtWidgets.framework/Headers/QWidget \
		../Qt/6.6.0/macos/lib/QtWidgets.framework/Headers/qwidget.h \
		../Qt/6.6.0/macos/lib/QtCore.framework/Headers/QTimer \
		../Qt/6.6.0/macos/lib/QtCore.framework/Headers/qtimer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

spider.o: spider.cpp spider.h \
		../Qt/6.6.0/macos/lib/QtCore.framework/Headers/QObject \
		../Qt/6.6.0/macos/lib/QtCore.framework/Headers/qobject.h \
		../Qt/6.6.0/macos/lib/QtCore.framework/Headers/QPoint \
		../Qt/6.6.0/macos/lib/QtCore.framework/Headers/qpoint.h \
		../Qt/6.6.0/macos/lib/QtCore.framework/Headers/QLine \
		../Qt/6.6.0/macos/lib/QtCore.framework/Headers/qline.h \
		../Qt/6.6.0/macos/lib/QtCore.framework/Headers/QRect \
		../Qt/6.6.0/macos/lib/QtCore.framework/Headers/qrect.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o spider.o spider.cpp

widget.o: widget.cpp widget.h \
		../Qt/6.6.0/macos/lib/QtWidgets.framework/Headers/QWidget \
		../Qt/6.6.0/macos/lib/QtWidgets.framework/Headers/qwidget.h \
		../Qt/6.6.0/macos/lib/QtCore.framework/Headers/QTimer \
		../Qt/6.6.0/macos/lib/QtCore.framework/Headers/qtimer.h \
		spider.h \
		../Qt/6.6.0/macos/lib/QtCore.framework/Headers/QObject \
		../Qt/6.6.0/macos/lib/QtCore.framework/Headers/qobject.h \
		../Qt/6.6.0/macos/lib/QtCore.framework/Headers/QPoint \
		../Qt/6.6.0/macos/lib/QtCore.framework/Headers/qpoint.h \
		../Qt/6.6.0/macos/lib/QtCore.framework/Headers/QLine \
		../Qt/6.6.0/macos/lib/QtCore.framework/Headers/qline.h \
		../Qt/6.6.0/macos/lib/QtCore.framework/Headers/QRect \
		../Qt/6.6.0/macos/lib/QtCore.framework/Headers/qrect.h \
		../Qt/6.6.0/macos/lib/QtGui.framework/Headers/QPainter \
		../Qt/6.6.0/macos/lib/QtGui.framework/Headers/qpainter.h \
		../Qt/6.6.0/macos/lib/QtGui.framework/Headers/QKeyEvent \
		../Qt/6.6.0/macos/lib/QtGui.framework/Headers/qevent.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o widget.o widget.cpp

moc_spider.o: moc_spider.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_spider.o moc_spider.cpp

moc_widget.o: moc_widget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_widget.o moc_widget.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/TaskSpider/bin || mkdir -p $(INSTALL_ROOT)/opt/TaskSpider/bin
	$(DEL_FILE) -r $(INSTALL_ROOT)/opt/TaskSpider/bin/TaskSpider.app
	
	$(QINSTALL) TaskSpider.app $(INSTALL_ROOT)/opt/TaskSpider/bin/TaskSpider.app

uninstall_target: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/opt/TaskSpider/bin/TaskSpider.app
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/TaskSpider/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

.SUFFIXES:

